SELECT 
    CONNECTION_ID,
    HOST,
    PORT,
    USER_NAME,
    CLIENT_HOST,
    CLIENT_IP,
    CONNECT_TIME,
    CONNECTION_STATUS,
    IDLE_TIME,
    LAST_ACTION_TIME,
    TRANSACTION_ID,
    UPDATE_TRANSACTION_ID,
    AUTO_COMMIT
FROM SYS.M_CONNECTIONS
WHERE CONNECTION_ID IN (300174, 361719, 318506, 317758, 300112)
ORDER BY CONNECT_TIME;